python count_targets-dr9.py LRG south
python count_targets-dr9.py LRG north
python count_targets-dr9.py LGE south
python count_targets-dr9.py LGE north
python count_targets-dr9.py ELG south
python count_targets-dr9.py ELG north
python count_targets-dr9.py QSO south
python count_targets-dr9.py QSO north
python count_targets-dr9.py BGS_ANY south
python count_targets-dr9.py BGS_ANY north